name: Run tests

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v3

            -   name: Setup .NET
                uses: actions/setup-dotnet@v3
                with:
                    dotnet-version: 8.0.x

            -   name: Restore
                run: dotnet restore ./Greenfield.sln

            -   name: Build
                run: dotnet build ./Greenfield.sln --no-restore

            -   name: Test
                run: dotnet test ./Greenfield.sln --no-build
        